multithread:
    status: true
    workers: 16
lastFM:
    api_key: 
genius:
    user_token: 
discogs:
    user_token: 
spotify:
    client_id: 
    client_secret: 
detectlanguage:
    api_key: 
paths:
    input: /Users/wilfredcho/Work/SongMind/Music/
    output: ./Copy/
logs:
    path: ./
    topic:
         - info
         - error
    size: 5242880
    backup: 100
split: ' ft. | feat. | ft | feat_ | \[| \('
tries: 10
genre:
    match_ratio: 85
    main:
        - 00s
        - 60s
        - 70s
        - 80s
        - 90s
        - 2000s
        - acoustic
        - acoustic pop
        - alternative
        - alternative pop
        - alternative r&b
        - alternative rock
        - australian pop
        - blues
        - christian
        - classical
        - country
        - dance
        - disney
        - deep house
        - easy listening
        - electronic
        - folk
        - funk
        - hip hop
        - indie
        - indie rock
        - jazz
        - metal
        - oldies
        - party
        - pop
        - pop rock
        - punk
        - rap
        - reggae
        - r&b
        - rnb
        - rock
        - soul
        - trap
    pair:
        aa: afar
        ab: abkhazian
        af: afrikaans
        ak: akan
        am: amharic
        ar: arabic
        as: assamese
        ay: aymara
        az: azerbaijani
        ba: bashkir
        be: belarusian
        bg: bulgarian
        bh: bihari
        bi: bislama
        bangla: bengali
        bn: bengali
        bo: tibetan 
        br: breton
        bs: bosnian
        bug: buginese
        ca: catalan
        ceb: cebuano
        chr: cherokee
        co: corsican
        crs: seselwa
        cs: czech
        cy: welsh
        da: danish
        de: german
        dv: dhivehi
        dz: dzongkha
        egy: egyptian
        el: greek
        en: english
        eo: esperanto
        es: spanish
        et: estonian
        eu: basque
        fa: persian
        fi: finnish
        fj: fijian
        fo: faroese
        fr: french
        fy: frisian
        ga: irish
        gd: scots gaelic
        gl: galician
        gn: guarani
        got: gothic
        gu: gujarati
        gv: manx
        ha: hausa
        haw: hawaiian
        hi: hindi
        hmn: hmong
        hr: croatian
        ht: haitian creole
        hu: hungarian
        hy: armenian
        ia: interlingua
        id: indonesian
        ie: interlingue
        ig: igbo
        ik: inupiak
        is: icelandic
        it: italian
        iu: inuktitut
        iw: hebrew
        ja: japanese
        jw: javanese
        ka: georgian
        kha: khasi
        kk: kazakh
        kl: greenlandic
        km: khmer
        kn: kannada
        ko: korean
        ks: kashmiri
        ku: kurdish
        ky: kyrgyz
        la: latin
        lb: luxembourgish
        lg: ganda
        lif: limbu
        ln: lingala
        lo: laothian
        lt: lithuanian
        lv: latvian
        mfe: mauritian creole
        mg: malagasy
        mi: maori
        mk: macedonian
        ml: malayalam
        mn: mongolian
        mr: marathi
        ms: malay
        mt: maltese
        my: burmese
        na: nauru
        ne: nepali
        nl: dutch
        no: norwegian
        nr: ndebele
        nso: pedi
        ny: nyanja
        oc: occitan
        om: oromo
        or: oriya
        pa: punjabi
        pl: polish
        ps: pashto
        pt: portuguese
        qu: quechua
        rm: rhaeto romance
        rn: rundi
        ro: romanian
        ru: russian
        rw: kinyarwanda
        sa: sanskrit
        sco: scots
        sd: sindhi
        sg: sango
        si: sinhalese
        sk: slovak
        sl: slovenian
        sm: samoan
        sn: shona
        so: somali
        sq: albanian
        sr: serbian
        ss: siswant
        st: sesotho
        su: sundanese
        sv: swedish
        sw: swahili
        syr: syriac
        ta: tamil
        te: telugu
        tg: tajik
        th: thai
        ti: tigrinya
        tk: turkmen
        tl: tagalog
        tlh: klingon
        tn: tswana
        to: tonga
        tr: turkish
        ts: tsonga
        tt: tatar
        ug: uighur
        uk: ukrainian
        ur: urdu
        uz: uzbek
        ve: venda
        vi: vietnamese
        vo: volapuk
        war: waray philippines
        wo: wolof
        xh: xhosa
        yi: yiddish
        yo: yoruba
        za: zhuang
        zh: chinese simplified
        zh-Hant: chinese traditional
        zu: zulu
        album rock: rock
        alternative hip hop: hip hop
        atl hip hop: hip hop
        alternative country: country
        alternative r&b: alternative rnb
        bass trap: trap
        conscious hip hop: hip hop
        contemporary gospel: christian
        east coast hip hop: hip hop
        electronica: electronic
        garage rock: rock
        hip-hop: hip hop
        indie cafe pop: indie
        indie pop: indie
        indie pop rap: indie
        indie r&b: indie
        j-alternative: japanese
        japanese r&b: japanese
        jpop: j-pop
        k-hop: korean
        k-pop: korean
        korean pop: korean
        oldie: oldies
        r&b: rnb
        smooth jazz: jazz
        vocal jazz: jazz