multithread:
    status: true
    workers: 16
lastFM:
    api_key: 
genius:
    user_token: 
discogs:
    user_token: 
spotify:
    client_id: 
    client_secret: 
detectlanguage:
    api_key: 
paths:
    input: /Users/wilfredcho/Work/SongMind/Music/
    output: ./Copy/
logs:
    path: ./
    topic:
         - info
         - error
    size: 5242880
    backup: 100
split: ' ft. | feat. | ft | feat_ | \[| \('
tries: 10
genre:
    match_ratio: 85
    main:
        - 00s
        - 60s
        - 70s
        - 80s
        - 90s
        - 2000s
        - acoustic
        - acoustic pop
        - alternative
        - alternative pop
        - alternative r&b
        - alternative rock
        - australian pop
        - blues
        - christian
        - classical
        - country
        - dance
        - disney
        - deep house
        - easy listening
        - electronic
        - folk
        - funk
        - hip hop
        - indie
        - indie rock
        - jazz
        - metal
        - oldies
        - party
        - pop
        - pop rock
        - punk
        - rap
        - reggae
        - r&b
        - rnb
        - rock
        - soul
        - trap