multithread:
    status: true
    workers: 8
lastFM:
    api_key: 
genius:
    user_token: 
discogs:
    user_token: 
spotify:
    client_id: 
    client_secret: 
paths:
    input: ~/Work/SongMind/Music/
    output: ./Copy/
logs:
    path: ./
    topic:
         - info
         - error
    size: 5242880
    backup: 100
split: ' ft. | feat. | ft | feat_ | \('
tries: 10
genre:
    main:
        - 60s
        - 70s
        - 80s
        - alternative
        - blues
        - christian
        - country
        - dance
        - deep house
        - easy listening
        - electronic
        - folk
        - funk
        - hip hop
        - jazz
        - indie
        - metal
        - pop
        - punk
        - r&b
        - rap
        - reggae
        - rock
        - soul